/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /media/psf/Home/SVNReps/HBPGit/SimulatorPrototype/ros_ws/src/simulation_control_server/srv/StartSimulation.srv
 *
 */


#ifndef SIMULATION_CONTROL_SERVER_MESSAGE_STARTSIMULATIONRESPONSE_H
#define SIMULATION_CONTROL_SERVER_MESSAGE_STARTSIMULATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulation_control_server
{
template <class ContainerAllocator>
struct StartSimulationResponse_
{
  typedef StartSimulationResponse_<ContainerAllocator> Type;

  StartSimulationResponse_()
    : success(false)
    , error_string()  {
    }
  StartSimulationResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_string(_alloc)  {
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_string_type;
  _error_string_type error_string;




  typedef boost::shared_ptr< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct StartSimulationResponse_

typedef ::simulation_control_server::StartSimulationResponse_<std::allocator<void> > StartSimulationResponse;

typedef boost::shared_ptr< ::simulation_control_server::StartSimulationResponse > StartSimulationResponsePtr;
typedef boost::shared_ptr< ::simulation_control_server::StartSimulationResponse const> StartSimulationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulation_control_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'simulation_control_server': ['/media/psf/Home/SVNReps/HBPGit/SimulatorPrototype/ros_ws/src/simulation_control_server/msg', '/media/psf/Home/SVNReps/HBPGit/SimulatorPrototype/ros_ws/src/simulation_control_server/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60bcc75747a184ebdba0e9c639470b9c";
  }

  static const char* value(const ::simulation_control_server::StartSimulationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60bcc75747a184ebULL;
  static const uint64_t static_value2 = 0xdba0e9c639470b9cULL;
};

template<class ContainerAllocator>
struct DataType< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulation_control_server/StartSimulationResponse";
  }

  static const char* value(const ::simulation_control_server::StartSimulationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
string error_string\n\
\n\
";
  }

  static const char* value(const ::simulation_control_server::StartSimulationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StartSimulationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulation_control_server::StartSimulationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulation_control_server::StartSimulationResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATION_CONTROL_SERVER_MESSAGE_STARTSIMULATIONRESPONSE_H
